#page title
page_title                                : WELTARE Strategies                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : # 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : # us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-34A125616E760572GMV6MH4Y                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                             # Enter Google Play Store URL.
presskit_download_link                    : https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-34A125616E760572GMV6MH4Y # https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.jpg #png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : WELTARE Strategies                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Votre Chatbot e-commerce clé en main à 384 € par mois                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Boostez vos ventes avec un chatbot e-commerce (Information produit, Commande & SAV, Gestion du compte client, Avis & feedbacks, Aide aux vendeurs...)  #Convertissez vos abonnés en investisseurs en les dirigeant vers les liens pertinents (site, boutique en ligne, articles...) # Write a short tagline for your app.
enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : WELTARE Strategies # Emil Baehr                                
your_link                                 : https://www.linkedin.com/company/weltare-strategies/?viewAsMember=true # https://emilbaehr.com                     
your_city                                 : Paris # Copenhagen                                
email_address                             : adoucoure@dr.com # emil.baehr@gmail.com
facebook_username                         : WELTAREStrategies/                                          
instagram_username                        : weltare_strategies # ebaehr
twitter_username                          : WELTAREmanager # ebaehr
github_username                           : weltare # emilbaehr
youtube_username                          : weltarestrategies5487
mastodon_link                             : # https://mastodon.social/@ebaehr



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Quoi ?
    description                           : Le seul assistant virtuel de relation client simple d’utilisation qui permet à vos clients de trouver rapidement une réponse à leur question, une page spécifique ou un produit.
    fontawesome_icon_name                 : robot
    
  - title                                 : Pourquoi ?
    description                           : Le but de notre chatbot est de permettre de profiter de la révolution de l'Intelligence Artificiele pour radicalement fluidifier le parcours de vos clients sur vos réseaux sociaux afin d'améliorer votre stratégie de conversion.
    fontawesome_icon_name                 : comments-dollar

  - title                                 : Combien ?
    description                           : Obtenez en moyenne un taux de conversion 10 fois supérieur, 75% de taux d'automatisation, 30% réduction des coûts d'exploitation, 25% de croissance de la satisfaction client et réduisez les temps d'attente des clients jusqu'à 90%.
    fontawesome_icon_name                 : arrow-trend-up

  - title                                 : Automatic Icon and Metadata
    description                           : Enter iOS app ID in the _config.yml file to automatically fetch app icon, price and App Store Link.
    fontawesome_icon_name                 : sync

  - title                                 : Easy to Tweak
    description                           : Tweak accent color, images, icons and transparency via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : adjust
  
  - title                                 : Feature List
    description                           : Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : star

  - title                                 : Smart App Banner
    description                           : Display a smart app banner on iOS devices.
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : Social Links
    description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : link

  - title                                 : FontAwesome Support
    description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
